// Code generated by qtc from "homepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Home page template. Implements BasePage methods.
//

//line ../../internal/templates/homepage.qtpl:3
package templates

//line ../../internal/templates/homepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../internal/templates/homepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../internal/templates/homepage.qtpl:4
type HomePage struct {
	Subjects []string
}

//line ../../internal/templates/homepage.qtpl:10
func (p *HomePage) StreamSubpage(qw422016 *qt422016.Writer) {
//line ../../internal/templates/homepage.qtpl:10
	qw422016.N().S(`
	
`)
//line ../../internal/templates/homepage.qtpl:12
}

//line ../../internal/templates/homepage.qtpl:12
func (p *HomePage) WriteSubpage(qq422016 qtio422016.Writer) {
//line ../../internal/templates/homepage.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/homepage.qtpl:12
	p.StreamSubpage(qw422016)
//line ../../internal/templates/homepage.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/homepage.qtpl:12
}

//line ../../internal/templates/homepage.qtpl:12
func (p *HomePage) Subpage() string {
//line ../../internal/templates/homepage.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/homepage.qtpl:12
	p.WriteSubpage(qb422016)
//line ../../internal/templates/homepage.qtpl:12
	qs422016 := string(qb422016.B)
//line ../../internal/templates/homepage.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/homepage.qtpl:12
	return qs422016
//line ../../internal/templates/homepage.qtpl:12
}

//line ../../internal/templates/homepage.qtpl:14
func (p *HomePage) StreamTitle(qw422016 *qt422016.Writer) {
//line ../../internal/templates/homepage.qtpl:14
	qw422016.N().S(`
	Home
`)
//line ../../internal/templates/homepage.qtpl:16
}

//line ../../internal/templates/homepage.qtpl:16
func (p *HomePage) WriteTitle(qq422016 qtio422016.Writer) {
//line ../../internal/templates/homepage.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/homepage.qtpl:16
	p.StreamTitle(qw422016)
//line ../../internal/templates/homepage.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/homepage.qtpl:16
}

//line ../../internal/templates/homepage.qtpl:16
func (p *HomePage) Title() string {
//line ../../internal/templates/homepage.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/homepage.qtpl:16
	p.WriteTitle(qb422016)
//line ../../internal/templates/homepage.qtpl:16
	qs422016 := string(qb422016.B)
//line ../../internal/templates/homepage.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/homepage.qtpl:16
	return qs422016
//line ../../internal/templates/homepage.qtpl:16
}

//line ../../internal/templates/homepage.qtpl:18
func (p *HomePage) StreamSidebar(qw422016 *qt422016.Writer) {
//line ../../internal/templates/homepage.qtpl:18
	qw422016.N().S(`
	`)
//line ../../internal/templates/homepage.qtpl:19
	StreamSidebar(qw422016, p.Subjects, 99, "")
//line ../../internal/templates/homepage.qtpl:19
	qw422016.N().S(`
`)
//line ../../internal/templates/homepage.qtpl:20
}

//line ../../internal/templates/homepage.qtpl:20
func (p *HomePage) WriteSidebar(qq422016 qtio422016.Writer) {
//line ../../internal/templates/homepage.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/homepage.qtpl:20
	p.StreamSidebar(qw422016)
//line ../../internal/templates/homepage.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/homepage.qtpl:20
}

//line ../../internal/templates/homepage.qtpl:20
func (p *HomePage) Sidebar() string {
//line ../../internal/templates/homepage.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/homepage.qtpl:20
	p.WriteSidebar(qb422016)
//line ../../internal/templates/homepage.qtpl:20
	qs422016 := string(qb422016.B)
//line ../../internal/templates/homepage.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/homepage.qtpl:20
	return qs422016
//line ../../internal/templates/homepage.qtpl:20
}

//line ../../internal/templates/homepage.qtpl:22
func (p *HomePage) StreamBody(qw422016 *qt422016.Writer) {
//line ../../internal/templates/homepage.qtpl:22
	qw422016.N().S(`
	<div>
        <br>
		<i>Click on one of the links in the sidebar</i>
	</div>
`)
//line ../../internal/templates/homepage.qtpl:27
}

//line ../../internal/templates/homepage.qtpl:27
func (p *HomePage) WriteBody(qq422016 qtio422016.Writer) {
//line ../../internal/templates/homepage.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/homepage.qtpl:27
	p.StreamBody(qw422016)
//line ../../internal/templates/homepage.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/homepage.qtpl:27
}

//line ../../internal/templates/homepage.qtpl:27
func (p *HomePage) Body() string {
//line ../../internal/templates/homepage.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/homepage.qtpl:27
	p.WriteBody(qb422016)
//line ../../internal/templates/homepage.qtpl:27
	qs422016 := string(qb422016.B)
//line ../../internal/templates/homepage.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/homepage.qtpl:27
	return qs422016
//line ../../internal/templates/homepage.qtpl:27
}
