// Code generated by qtc from "subject.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line ../../internal/templates/subject.qtpl:3
package templates

//line ../../internal/templates/subject.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../internal/templates/subject.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../internal/templates/subject.qtpl:4
type MainPage struct {
	Subjects []string
}

//line ../../internal/templates/subject.qtpl:10
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line ../../internal/templates/subject.qtpl:10
	qw422016.N().S(`
	Main page
`)
//line ../../internal/templates/subject.qtpl:12
}

//line ../../internal/templates/subject.qtpl:12
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line ../../internal/templates/subject.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/subject.qtpl:12
	p.StreamTitle(qw422016)
//line ../../internal/templates/subject.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/subject.qtpl:12
}

//line ../../internal/templates/subject.qtpl:12
func (p *MainPage) Title() string {
//line ../../internal/templates/subject.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/subject.qtpl:12
	p.WriteTitle(qb422016)
//line ../../internal/templates/subject.qtpl:12
	qs422016 := string(qb422016.B)
//line ../../internal/templates/subject.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/subject.qtpl:12
	return qs422016
//line ../../internal/templates/subject.qtpl:12
}

//line ../../internal/templates/subject.qtpl:15
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line ../../internal/templates/subject.qtpl:15
	qw422016.N().S(`
	<h1>Main page</h1>
	<div>
		Click links below:
		<ul>
			`)
//line ../../internal/templates/subject.qtpl:20
	for _, subj := range p.Subjects {
//line ../../internal/templates/subject.qtpl:20
		qw422016.N().S(`
				<li><a href="`)
//line ../../internal/templates/subject.qtpl:21
		qw422016.E().S(subj)
//line ../../internal/templates/subject.qtpl:21
		qw422016.N().S(`/">`)
//line ../../internal/templates/subject.qtpl:21
		qw422016.E().S(subj)
//line ../../internal/templates/subject.qtpl:21
		qw422016.N().S(`</a></li>
			`)
//line ../../internal/templates/subject.qtpl:22
	}
//line ../../internal/templates/subject.qtpl:22
	qw422016.N().S(`
		</ul>
	</div>
`)
//line ../../internal/templates/subject.qtpl:25
}

//line ../../internal/templates/subject.qtpl:25
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line ../../internal/templates/subject.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/subject.qtpl:25
	p.StreamBody(qw422016)
//line ../../internal/templates/subject.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/subject.qtpl:25
}

//line ../../internal/templates/subject.qtpl:25
func (p *MainPage) Body() string {
//line ../../internal/templates/subject.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/subject.qtpl:25
	p.WriteBody(qb422016)
//line ../../internal/templates/subject.qtpl:25
	qs422016 := string(qb422016.B)
//line ../../internal/templates/subject.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/subject.qtpl:25
	return qs422016
//line ../../internal/templates/subject.qtpl:25
}
