// Code generated by qtc from "subject.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Subject page template. Implements BasePage methods.
//

//line ../../internal/templates/subject.qtpl:3
package templates

//line ../../internal/templates/subject.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../internal/templates/subject.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../internal/templates/subject.qtpl:4
type SubjectPage struct {
	Subjects []string
	Subject  string
	Files    string
}

//line ../../internal/templates/subject.qtpl:12
func (p *SubjectPage) StreamSubpage(qw422016 *qt422016.Writer) {
//line ../../internal/templates/subject.qtpl:12
	qw422016.N().S(`
	../
`)
//line ../../internal/templates/subject.qtpl:14
}

//line ../../internal/templates/subject.qtpl:14
func (p *SubjectPage) WriteSubpage(qq422016 qtio422016.Writer) {
//line ../../internal/templates/subject.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/subject.qtpl:14
	p.StreamSubpage(qw422016)
//line ../../internal/templates/subject.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/subject.qtpl:14
}

//line ../../internal/templates/subject.qtpl:14
func (p *SubjectPage) Subpage() string {
//line ../../internal/templates/subject.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/subject.qtpl:14
	p.WriteSubpage(qb422016)
//line ../../internal/templates/subject.qtpl:14
	qs422016 := string(qb422016.B)
//line ../../internal/templates/subject.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/subject.qtpl:14
	return qs422016
//line ../../internal/templates/subject.qtpl:14
}

//line ../../internal/templates/subject.qtpl:16
func (p *SubjectPage) StreamTitle(qw422016 *qt422016.Writer) {
//line ../../internal/templates/subject.qtpl:16
	qw422016.N().S(`
	`)
//line ../../internal/templates/subject.qtpl:17
	qw422016.E().S(p.Subject)
//line ../../internal/templates/subject.qtpl:17
	qw422016.N().S(`
`)
//line ../../internal/templates/subject.qtpl:18
}

//line ../../internal/templates/subject.qtpl:18
func (p *SubjectPage) WriteTitle(qq422016 qtio422016.Writer) {
//line ../../internal/templates/subject.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/subject.qtpl:18
	p.StreamTitle(qw422016)
//line ../../internal/templates/subject.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/subject.qtpl:18
}

//line ../../internal/templates/subject.qtpl:18
func (p *SubjectPage) Title() string {
//line ../../internal/templates/subject.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/subject.qtpl:18
	p.WriteTitle(qb422016)
//line ../../internal/templates/subject.qtpl:18
	qs422016 := string(qb422016.B)
//line ../../internal/templates/subject.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/subject.qtpl:18
	return qs422016
//line ../../internal/templates/subject.qtpl:18
}

//line ../../internal/templates/subject.qtpl:20
func (p *SubjectPage) StreamSidebar(qw422016 *qt422016.Writer) {
//line ../../internal/templates/subject.qtpl:20
	qw422016.N().S(`
	`)
//line ../../internal/templates/subject.qtpl:21
	StreamSidebar(qw422016, p.Subjects, 99, "../")
//line ../../internal/templates/subject.qtpl:21
	qw422016.N().S(`
`)
//line ../../internal/templates/subject.qtpl:22
}

//line ../../internal/templates/subject.qtpl:22
func (p *SubjectPage) WriteSidebar(qq422016 qtio422016.Writer) {
//line ../../internal/templates/subject.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/subject.qtpl:22
	p.StreamSidebar(qw422016)
//line ../../internal/templates/subject.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/subject.qtpl:22
}

//line ../../internal/templates/subject.qtpl:22
func (p *SubjectPage) Sidebar() string {
//line ../../internal/templates/subject.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/subject.qtpl:22
	p.WriteSidebar(qb422016)
//line ../../internal/templates/subject.qtpl:22
	qs422016 := string(qb422016.B)
//line ../../internal/templates/subject.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/subject.qtpl:22
	return qs422016
//line ../../internal/templates/subject.qtpl:22
}

//line ../../internal/templates/subject.qtpl:24
func (p *SubjectPage) StreamBody(qw422016 *qt422016.Writer) {
//line ../../internal/templates/subject.qtpl:24
	qw422016.N().S(`
	<script>
		const items = `)
//line ../../internal/templates/subject.qtpl:26
	qw422016.N().S(p.Files)
//line ../../internal/templates/subject.qtpl:26
	qw422016.N().S(`
	</script>
	<h1>`)
//line ../../internal/templates/subject.qtpl:28
	qw422016.E().S(p.Subject)
//line ../../internal/templates/subject.qtpl:28
	qw422016.N().S(`</h1>

	<div class="dropdown">
		<a class="btn btn-sm btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuDescription" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Filter by...
		</a>

		<div class="dropdown-menu" aria-labelledby="dropdownMenuDescription" id="dropdownMenuItems">
			<!--<a class="dropdown-item" href="#">Something else here</a>-->
		</div>
	</div>

	<br>

	<noscript>Enable JavaScript for this page to work</noscript>
	<div id="buildArea"></div>
`)
//line ../../internal/templates/subject.qtpl:44
}

//line ../../internal/templates/subject.qtpl:44
func (p *SubjectPage) WriteBody(qq422016 qtio422016.Writer) {
//line ../../internal/templates/subject.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/templates/subject.qtpl:44
	p.StreamBody(qw422016)
//line ../../internal/templates/subject.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/templates/subject.qtpl:44
}

//line ../../internal/templates/subject.qtpl:44
func (p *SubjectPage) Body() string {
//line ../../internal/templates/subject.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/templates/subject.qtpl:44
	p.WriteBody(qb422016)
//line ../../internal/templates/subject.qtpl:44
	qs422016 := string(qb422016.B)
//line ../../internal/templates/subject.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/templates/subject.qtpl:44
	return qs422016
//line ../../internal/templates/subject.qtpl:44
}
